dataRoot: ./data

listen: true
port: 8000

browserLaunch:
  enabled: false

protocol:
  ipv4: true
  ipv6: false

heartbeatInterval: 30

securityOverride: true
whitelistMode: false
enableForwardedWhitelist: true
whitelistDockerHosts: true

cors:
  enabled: true
  origin:
    - "*"
  methods:
    - "GET"
    - "POST"
    - "OPTIONS"
  allowedHeaders:
    - "Content-Type"
    - "X-CSRF-Token"
    - "Authorization"
  exposedHeaders: []
  credentials: true
  maxAge: null
