CREATE TABLE IF NOT EXISTS app_illustration_work (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(160) NOT NULL,
    slug VARCHAR(180) NOT NULL,
    category VARCHAR(64) NOT NULL DEFAULT '原创',
    tags_json TEXT NULL,
    description TEXT NULL,
    cover_url VARCHAR(1024) NOT NULL,
    image_url VARCHAR(1024) NOT NULL,
    content_level VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
    status VARCHAR(20) NOT NULL DEFAULT 'PUBLISHED',
    source VARCHAR(20) NOT NULL DEFAULT 'ADMIN',
    submitter_user_id BIGINT NULL,
    submitter_name VARCHAR(120) NULL,
    audit_note VARCHAR(500) NULL,
    recommended TINYINT(1) NOT NULL DEFAULT 0,
    sort_order INT NOT NULL DEFAULT 0,
    view_count BIGINT NOT NULL DEFAULT 0,
    like_count BIGINT NOT NULL DEFAULT 0,
    reviewed_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    UNIQUE KEY uk_app_illustration_work_slug (slug),
    KEY idx_app_illustration_work_status_level (status, content_level),
    KEY idx_app_illustration_work_category (category),
    KEY idx_app_illustration_work_recommended (recommended, sort_order),
    KEY idx_app_illustration_work_submitter (submitter_user_id),
    KEY idx_app_illustration_work_created (created_at)
);
