CREATE TABLE IF NOT EXISTS app_voice_stat_event (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NULL,
    scope VARCHAR(16) NOT NULL DEFAULT '',
    provider_source VARCHAR(32) NOT NULL DEFAULT '',
    model_name VARCHAR(255) NOT NULL DEFAULT '',
    voice_name VARCHAR(255) NOT NULL DEFAULT '',
    template_code VARCHAR(64) NOT NULL DEFAULT '',
    status VARCHAR(16) NOT NULL DEFAULT 'SUCCESS',
    event_day DATE NOT NULL,
    request_fingerprint CHAR(64) NOT NULL DEFAULT '',
    text_chars INT NOT NULL DEFAULT 0,
    audio_bytes INT NOT NULL DEFAULT 0,
    latency_ms INT NOT NULL DEFAULT 0,
    cache_hit TINYINT(1) NOT NULL DEFAULT 0,
    duplicate_request TINYINT(1) NOT NULL DEFAULT 0,
    error_code VARCHAR(64) NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_voice_stat_day_scope (event_day, scope),
    KEY idx_voice_stat_scope_status_day (scope, status, event_day),
    KEY idx_voice_stat_scope_cache_day (scope, cache_hit, event_day),
    KEY idx_voice_stat_scope_dup_day (scope, duplicate_request, event_day),
    KEY idx_voice_stat_scope_fingerprint (scope, request_fingerprint, event_day)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
