CREATE TABLE app_generation_model_pricing (
    id BIGINT NOT NULL AUTO_INCREMENT,
    provider_key VARCHAR(80) NOT NULL,
    model_pattern VARCHAR(255) NOT NULL,
    version VARCHAR(64) NOT NULL,
    currency CHAR(3) NOT NULL DEFAULT 'USD',
    input_usd_per_million_tokens DECIMAL(20, 10) NOT NULL DEFAULT 0,
    output_usd_per_million_tokens DECIMAL(20, 10) NOT NULL DEFAULT 0,
    effective_from DATETIME(6) NOT NULL,
    effective_to DATETIME(6) NULL,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    note VARCHAR(255) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_generation_pricing_version (
        provider_key,
        model_pattern,
        version,
        effective_from
    ),
    KEY idx_generation_pricing_lookup (provider_key, enabled, effective_from, effective_to)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE app_generation_attempt (
    id BIGINT NOT NULL AUTO_INCREMENT,
    generation_task_id BIGINT NULL,
    conversation_id BIGINT NULL,
    character_id BIGINT NULL,
    attempt_no INT NOT NULL,
    provider_key VARCHAR(80) NOT NULL,
    route_key VARCHAR(80) NOT NULL,
    provider_source VARCHAR(80) NULL,
    model VARCHAR(255) NULL,
    byok TINYINT(1) NOT NULL DEFAULT 0,
    was_fallback TINYINT(1) NOT NULL DEFAULT 0,
    started_at DATETIME(6) NOT NULL,
    first_token_at DATETIME(6) NULL,
    finished_at DATETIME(6) NOT NULL,
    ttft_ms INT NULL,
    duration_ms INT NOT NULL,
    http_status INT NULL,
    status VARCHAR(24) NOT NULL,
    error_code VARCHAR(80) NULL,
    prompt_tokens INT NULL,
    completion_tokens INT NULL,
    prompt_tokens_estimated TINYINT(1) NOT NULL DEFAULT 0,
    completion_tokens_estimated TINYINT(1) NOT NULL DEFAULT 0,
    pricing_id BIGINT NULL,
    pricing_version VARCHAR(64) NULL,
    currency CHAR(3) NULL,
    input_usd_per_million_tokens DECIMAL(20, 10) NULL,
    output_usd_per_million_tokens DECIMAL(20, 10) NULL,
    input_cost_usd DECIMAL(20, 10) NULL,
    output_cost_usd DECIMAL(20, 10) NULL,
    total_cost_usd DECIMAL(20, 10) NULL,
    cost_estimated TINYINT(1) NOT NULL DEFAULT 0,
    cost_partial TINYINT(1) NOT NULL DEFAULT 0,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_generation_attempt_started (started_at),
    KEY idx_generation_attempt_provider (provider_key, started_at),
    KEY idx_generation_attempt_model (model, started_at),
    KEY idx_generation_attempt_character (character_id, started_at),
    KEY idx_generation_attempt_route (route_key, started_at),
    KEY idx_generation_attempt_status (status, started_at),
    KEY idx_generation_attempt_task (generation_task_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
