CREATE TABLE IF NOT EXISTS app_android_release (
    id BIGINT NOT NULL AUTO_INCREMENT,
    app_id VARCHAR(64) NOT NULL,
    package_name VARCHAR(191) NOT NULL,
    channel_code VARCHAR(32) NOT NULL DEFAULT 'official',
    version_name VARCHAR(32) NOT NULL,
    version_code INT NOT NULL,
    update_mode VARCHAR(16) NOT NULL DEFAULT 'NORMAL',
    min_supported_version_code INT NOT NULL DEFAULT 0,
    policy_revision INT NOT NULL DEFAULT 1,
    title VARCHAR(128) NOT NULL DEFAULT '',
    changelog TEXT NOT NULL,
    download_url VARCHAR(1024) NOT NULL,
    remind_later_hours INT NOT NULL DEFAULT 6,
    apk_size_bytes BIGINT NULL,
    apk_sha256 VARCHAR(64) NOT NULL DEFAULT '',
    status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    publish_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_android_release_version (app_id, package_name, channel_code, version_code),
    KEY idx_android_release_match (app_id, package_name, channel_code, status, publish_at, version_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
