CREATE TABLE app_external_cleanup_task (
    id CHAR(36) NOT NULL,
    task_key CHAR(64) NOT NULL,
    source_user_id BIGINT NOT NULL,
    resource_type VARCHAR(32) NOT NULL,
    primary_ref TEXT NOT NULL,
    secondary_ref TEXT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    attempt_count INT NOT NULL DEFAULT 0,
    max_attempts INT NOT NULL,
    next_attempt_at DATETIME(6) NULL,
    last_attempt_at DATETIME(6) NULL,
    locked_until DATETIME(6) NULL,
    lock_token CHAR(36) NULL,
    last_error TEXT NULL,
    completed_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_external_cleanup_task_key (task_key),
    KEY idx_external_cleanup_due (status, next_attempt_at),
    KEY idx_external_cleanup_lease (status, locked_until),
    KEY idx_external_cleanup_user (source_user_id, created_at)
);
