CREATE TABLE IF NOT EXISTS app_user_tts_voice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    request_id VARCHAR(64) NOT NULL,
    display_name VARCHAR(64) NOT NULL,
    provider_source VARCHAR(32) NOT NULL DEFAULT 'siliconflow',
    model_name VARCHAR(255) NOT NULL DEFAULT '',
    config_fingerprint VARCHAR(64) NOT NULL DEFAULT '',
    voice_uri VARCHAR(255) NOT NULL DEFAULT '',
    status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
    last_error VARCHAR(255) NOT NULL DEFAULT '',
    disabled BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    CONSTRAINT uk_app_user_tts_voice_request UNIQUE (user_id, request_id)
);

CREATE INDEX IF NOT EXISTS idx_app_user_tts_voice_owner
    ON app_user_tts_voice (user_id, deleted_at, status, updated_at);
CREATE INDEX IF NOT EXISTS idx_app_user_tts_voice_admin
    ON app_user_tts_voice (status, disabled, updated_at);

CREATE TABLE IF NOT EXISTS app_user_tts_voice_binding (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    scope_type VARCHAR(16) NOT NULL,
    character_id BIGINT NOT NULL DEFAULT 0,
    member_id BIGINT NOT NULL DEFAULT 0,
    voice_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_app_user_tts_voice_binding_scope UNIQUE (user_id, scope_type, character_id, member_id)
);

CREATE INDEX IF NOT EXISTS idx_app_user_tts_voice_binding_voice
    ON app_user_tts_voice_binding (voice_id);
CREATE INDEX IF NOT EXISTS idx_app_user_tts_voice_binding_owner
    ON app_user_tts_voice_binding (user_id, updated_at);
