CREATE TABLE app_h5_upload_asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_url VARCHAR(512) NOT NULL,
    relative_path VARCHAR(512) NOT NULL,
    owner_user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_h5_upload_asset_url UNIQUE (asset_url),
    CONSTRAINT uk_h5_upload_relative_path UNIQUE (relative_path),
    CONSTRAINT fk_h5_upload_asset_owner
        FOREIGN KEY (owner_user_id) REFERENCES app_user(id)
        ON DELETE RESTRICT
);

CREATE INDEX idx_h5_upload_asset_owner ON app_h5_upload_asset(owner_user_id, created_at);
