-- V93 (H2): daily check-in

ALTER TABLE app_h5_user_profile_ext ADD COLUMN IF NOT EXISTS daily_chat_bonus INT NOT NULL DEFAULT 0;
ALTER TABLE app_h5_user_profile_ext ADD COLUMN IF NOT EXISTS daily_image_bonus INT NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS app_checkin_activity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(128) NOT NULL,
    enabled INT NOT NULL DEFAULT 1,
    start_at TIMESTAMP NULL,
    end_at TIMESTAMP NULL,
    audience VARCHAR(32) NOT NULL DEFAULT 'ALL_LOGIN',
    reward_score INT NOT NULL DEFAULT 0,
    reward_gold INT NOT NULL DEFAULT 0,
    reward_chat_bonus INT NOT NULL DEFAULT 0,
    reward_image_bonus INT NOT NULL DEFAULT 0,
    streak_rules_json CLOB NULL,
    timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai',
    note VARCHAR(512) NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_checkin_activity_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS app_checkin_claim (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    activity_id BIGINT NOT NULL,
    biz_date DATE NOT NULL,
    streak_day INT NOT NULL DEFAULT 1,
    reward_score INT NOT NULL DEFAULT 0,
    reward_gold INT NOT NULL DEFAULT 0,
    reward_chat_bonus INT NOT NULL DEFAULT 0,
    reward_image_bonus INT NOT NULL DEFAULT 0,
    reward_json CLOB NULL,
    ledger_idempotency_key VARCHAR(96) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_checkin_claim_user_activity_day UNIQUE (user_id, activity_id, biz_date)
);

CREATE INDEX IF NOT EXISTS idx_checkin_claim_activity_day ON app_checkin_claim(activity_id, biz_date);

MERGE INTO app_checkin_activity (
    code, name, enabled, audience,
    reward_score, reward_gold, reward_chat_bonus, reward_image_bonus,
    streak_rules_json, timezone, note
) KEY (code)
VALUES (
    'daily_checkin',
    'Daily Check-in',
    1,
    'ALL_LOGIN',
    10,
    0,
    2,
    0,
    '[{"day":3,"score":5,"gold":0,"chatBonus":0,"imageBonus":0},{"day":7,"score":20,"gold":0,"chatBonus":1,"imageBonus":0}]',
    'Asia/Shanghai',
    'Default daily check-in'
);
