CREATE TABLE IF NOT EXISTS app_android_release (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id VARCHAR(64) NOT NULL,
    package_name VARCHAR(191) NOT NULL,
    channel_code VARCHAR(32) NOT NULL DEFAULT 'official',
    version_name VARCHAR(32) NOT NULL,
    version_code INT NOT NULL,
    update_mode VARCHAR(16) NOT NULL DEFAULT 'NORMAL',
    min_supported_version_code INT NOT NULL DEFAULT 0,
    policy_revision INT NOT NULL DEFAULT 1,
    title VARCHAR(128) NOT NULL DEFAULT '',
    changelog CLOB NOT NULL,
    download_url VARCHAR(1024) NOT NULL,
    remind_later_hours INT NOT NULL DEFAULT 6,
    apk_size_bytes BIGINT NULL,
    apk_sha256 VARCHAR(64) NOT NULL DEFAULT '',
    status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    publish_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_android_release_version UNIQUE (app_id, package_name, channel_code, version_code)
);

CREATE INDEX IF NOT EXISTS idx_android_release_match
    ON app_android_release(app_id, package_name, channel_code, status, publish_at, version_code);
